services:
    _defaults:
        autowire: true

    TweedeGolf\PrometheusClient\Storage\ApcuAdapter: ~
    TweedeGolf\PrometheusClient\Storage\ApcAdapter: ~

    Ijanki\Bundle\PrometheusBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Ijanki\Bundle\PrometheusBundle\EventSubscriber\EventSubscriber:
        tags:
        - { name: kernel.event_subscriber }
